// backend/internal/hrm/calendar/model.go
package calendar

import (
	"errors"
	"time"
)

type EventType string

const (
	TypeHoliday         EventType = "holiday"
	TypeTraining        EventType = "training"
	TypeCompanyEvent    EventType = "company_event"
	TypeTeamEvent       EventType = "team_event"
	TypeDeadline        EventType = "deadline"
	TypeBirthday        EventType = "birthday"
	TypeWorkAnniversary EventType = "work_anniversary"
	TypeCustom          EventType = "custom"
)

func (t EventType) IsValid() bool {
	switch t {
	case TypeHoliday, TypeTraining, TypeCompanyEvent, TypeTeamEvent, TypeDeadline, TypeBirthday, TypeWorkAnniversary, TypeCustom:
		return true
	}
	return false
}

type EventStatus string

const (
	StatusUpcoming  EventStatus = "upcoming"
	StatusOngoing   EventStatus = "ongoing"
	StatusCompleted EventStatus = "completed"
	StatusCancelled EventStatus = "cancelled"
)

type ScopeType string

const (
	ScopeOrganization ScopeType = "organization"
	ScopeDepartment   ScopeType = "department"
	ScopeIndividual   ScopeType = "individual"
)

// CalendarEvent is an HR calendar entry.
type CalendarEvent struct {
	ID              string      `db:"id"               json:"id"`
	PublicID        string      `db:"public_id"        json:"public_id"`
	OrgID           string      `db:"org_id"           json:"org_id"`
	Title           string      `db:"title"            json:"title"`
	Description     *string     `db:"description"      json:"description,omitempty"`
	EventType       EventType   `db:"event_type"       json:"event_type"`
	StartDate       string      `db:"start_date"       json:"start_date"`
	EndDate         string      `db:"end_date"         json:"end_date"`
	IsAllDay        bool        `db:"is_all_day"       json:"is_all_day"`
	StartTime       *string     `db:"start_time"       json:"start_time,omitempty"`
	EndTime         *string     `db:"end_time"         json:"end_time,omitempty"`
	Location        *string     `db:"location"         json:"location,omitempty"`
	ScopeType       ScopeType   `db:"scope_type"       json:"scope_type"`
	ScopeIDs        []string    `db:"scope_ids"        json:"scope_ids"`
	RequiresRSVP    bool        `db:"requires_rsvp"    json:"requires_rsvp"`
	RSVPDeadline    *string     `db:"rsvp_deadline"    json:"rsvp_deadline,omitempty"`
	OrganizerID     *string     `db:"organizer_id"     json:"organizer_id,omitempty"`
	IsAutoGenerated bool        `db:"is_auto_generated" json:"is_auto_generated"`
	Source          *string     `db:"source"           json:"source,omitempty"`
	SourceID        *string     `db:"source_id"        json:"source_id,omitempty"`
	Status          EventStatus `db:"status"           json:"status"`
	CreatedBy       string      `db:"created_by"       json:"created_by"`
	CreatedAt       time.Time   `db:"created_at"       json:"created_at"`
	UpdatedAt       time.Time   `db:"updated_at"       json:"updated_at"`
}

type CreateEventRequest struct {
	Title        string    `json:"title"`
	Description  *string   `json:"description"`
	EventType    EventType `json:"event_type"`
	StartDate    string    `json:"start_date"`
	EndDate      string    `json:"end_date"`
	IsAllDay     bool      `json:"is_all_day"`
	StartTime    *string   `json:"start_time"`
	EndTime      *string   `json:"end_time"`
	Location     *string   `json:"location"`
	ScopeType    ScopeType `json:"scope_type"`
	ScopeIDs     []string  `json:"scope_ids"`
	RequiresRSVP bool      `json:"requires_rsvp"`
	RSVPDeadline *string   `json:"rsvp_deadline"`
	OrganizerID  *string   `json:"organizer_id"`
}

type UpdateEventRequest struct {
	Title        *string      `json:"title"`
	Description  *string      `json:"description"`
	StartDate    *string      `json:"start_date"`
	EndDate      *string      `json:"end_date"`
	Location     *string      `json:"location"`
	RequiresRSVP *bool        `json:"requires_rsvp"`
	RSVPDeadline *string      `json:"rsvp_deadline"`
	Status       *EventStatus `json:"status"`
}

type EventListResponse struct {
	Events []*CalendarEvent `json:"events"`
	Total  int              `json:"total"`
}

var (
	ErrNotFound          = errors.New("calendar event not found")
	ErrTitleRequired     = errors.New("title is required")
	ErrInvalidEventType  = errors.New("invalid event_type")
	ErrStartDateRequired = errors.New("start_date is required (YYYY-MM-DD)")
	ErrEndDateRequired   = errors.New("end_date is required (YYYY-MM-DD)")
	ErrInvalidDate       = errors.New("date must be a valid YYYY-MM-DD")
	ErrEndBeforeStart    = errors.New("end_date must be >= start_date")
	ErrWrongStatus       = errors.New("action not allowed in current event status")
)
