// backend/internal/hrm/calendar/repository.go
package calendar

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Repository interface {
	FindAll(ctx context.Context, orgID, eventType, status string, fromDate, toDate string) ([]*CalendarEvent, error)
	FindByRef(ctx context.Context, orgID, ref string) (*CalendarEvent, error)
	Create(ctx context.Context, e *CalendarEvent) error
	Update(ctx context.Context, e *CalendarEvent) error
	UpdateStatus(ctx context.Context, id string, status EventStatus) error
	GetTargetEmployeeIDs(ctx context.Context, orgID string, scopeType ScopeType, scopeIDs []string) ([]string, error)
}

type repoImpl struct{ db *pgxpool.Pool }
func NewRepository(db *pgxpool.Pool) Repository { return &repoImpl{db: db} }

const sel = `id, public_id, org_id, title, description, event_type,
	to_char(start_date,'YYYY-MM-DD'), to_char(end_date,'YYYY-MM-DD'),
	is_all_day, start_time::text, end_time::text, location,
	scope_type, scope_ids,
	requires_rsvp, to_char(rsvp_deadline,'YYYY-MM-DD'),
	organizer_id, is_auto_generated, source, source_id::text,
	status, created_by, created_at, updated_at`

func scan(row pgx.Row) (*CalendarEvent, error) {
	e := &CalendarEvent{}
	err := row.Scan(
		&e.ID, &e.PublicID, &e.OrgID, &e.Title, &e.Description, &e.EventType,
		&e.StartDate, &e.EndDate,
		&e.IsAllDay, &e.StartTime, &e.EndTime, &e.Location,
		&e.ScopeType, &e.ScopeIDs,
		&e.RequiresRSVP, &e.RSVPDeadline,
		&e.OrganizerID, &e.IsAutoGenerated, &e.Source, &e.SourceID,
		&e.Status, &e.CreatedBy, &e.CreatedAt, &e.UpdatedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) { return nil, nil }
	if err != nil { return nil, err }
	if e.ScopeIDs == nil { e.ScopeIDs = []string{} }
	return e, nil
}

func (r *repoImpl) FindAll(ctx context.Context, orgID, eventType, status string, fromDate, toDate string) ([]*CalendarEvent, error) {
	q := `SELECT ` + sel + ` FROM hrm_calendar_events WHERE org_id=$1`
	args := []any{orgID}
	if eventType != "" { args = append(args, eventType); q += fmt.Sprintf(` AND event_type=$%d`, len(args)) }
	if status != "" { args = append(args, status); q += fmt.Sprintf(` AND status=$%d`, len(args)) }
	if fromDate != "" { args = append(args, fromDate); q += fmt.Sprintf(` AND end_date>=$%d::date`, len(args)) }
	if toDate != "" { args = append(args, toDate); q += fmt.Sprintf(` AND start_date<=$%d::date`, len(args)) }
	q += ` ORDER BY start_date ASC, created_at DESC`
	rows, err := r.db.Query(ctx, q, args...)
	if err != nil { return nil, fmt.Errorf("calendar: FindAll: %w", err) }
	defer rows.Close()
	list := make([]*CalendarEvent, 0)
	for rows.Next() { ev, err := scan(rows); if err != nil { return nil, err }; list = append(list, ev) }
	return list, rows.Err()
}

func (r *repoImpl) FindByRef(ctx context.Context, orgID, ref string) (*CalendarEvent, error) {
	return scan(r.db.QueryRow(ctx,
		`SELECT `+sel+` FROM hrm_calendar_events WHERE org_id=$1 AND (id::text=$2 OR public_id=$2)`,
		orgID, ref))
}

func (r *repoImpl) Create(ctx context.Context, e *CalendarEvent) error {
	if e.ScopeIDs == nil { e.ScopeIDs = []string{} }
	return r.db.QueryRow(ctx,
		`INSERT INTO hrm_calendar_events
		(org_id, title, description, event_type, start_date, end_date,
		 is_all_day, start_time, end_time, location, scope_type, scope_ids,
		 requires_rsvp, rsvp_deadline, organizer_id, is_auto_generated, source, source_id, status, created_by)
		VALUES ($1,$2,$3,$4,$5::date,$6::date,$7,$8::time,$9::time,$10,$11,$12,$13,$14::date,$15,$16,$17,$18,$19,$20)
		RETURNING id, public_id, created_at, updated_at`,
		e.OrgID, e.Title, e.Description, e.EventType, e.StartDate, e.EndDate,
		e.IsAllDay, e.StartTime, e.EndTime, e.Location, e.ScopeType, e.ScopeIDs,
		e.RequiresRSVP, e.RSVPDeadline, e.OrganizerID, e.IsAutoGenerated, e.Source, e.SourceID, e.Status, e.CreatedBy,
	).Scan(&e.ID, &e.PublicID, &e.CreatedAt, &e.UpdatedAt)
}

func (r *repoImpl) Update(ctx context.Context, e *CalendarEvent) error {
	return r.db.QueryRow(ctx,
		`UPDATE hrm_calendar_events SET
		title=$1, description=$2, start_date=$3::date, end_date=$4::date,
		location=$5, requires_rsvp=$6, rsvp_deadline=$7::date, updated_at=NOW()
		WHERE id=$8 AND org_id=$9 RETURNING updated_at`,
		e.Title, e.Description, e.StartDate, e.EndDate,
		e.Location, e.RequiresRSVP, e.RSVPDeadline, e.ID, e.OrgID,
	).Scan(&e.UpdatedAt)
}

func (r *repoImpl) UpdateStatus(ctx context.Context, id string, status EventStatus) error {
	_, err := r.db.Exec(ctx, `UPDATE hrm_calendar_events SET status=$1, updated_at=NOW() WHERE id=$2`, status, id)
	return err
}

func (r *repoImpl) GetTargetEmployeeIDs(ctx context.Context, orgID string, scopeType ScopeType, scopeIDs []string) ([]string, error) {
	var q string; var args []any
	switch scopeType {
	// Active employees resolve through hrm_employee_statuses.category. There is
	// no hrm_employees.status column — migration 00053 replaced it with
	// status_id, and querying the dropped column failed 42703, taking the whole
	// audience resolution with it.
	case ScopeOrganization:
		q = `SELECT e.id::text FROM hrm_employees e JOIN hrm_employee_statuses es ON es.id=e.status_id WHERE e.org_id=$1 AND es.category='active'`
		args = []any{orgID}
	case ScopeDepartment:
		q = `SELECT e.id::text FROM hrm_employees e JOIN hrm_employee_statuses es ON es.id=e.status_id WHERE e.org_id=$1 AND es.category='active' AND e.department_id=ANY($2::uuid[])`
		args = []any{orgID, scopeIDs}
	default:
		q = `SELECT id::text FROM hrm_employees WHERE org_id=$1 AND id::text=ANY($2)`; args = []any{orgID, scopeIDs}
	}
	rows, err := r.db.Query(ctx, q, args...)
	if err != nil { return nil, err }
	defer rows.Close()
	var ids []string
	for rows.Next() { var id string; _ = rows.Scan(&id); ids = append(ids, id) }
	return ids, rows.Err()
}
