-- +goose Up
-- +goose StatementBegin

-- ============================================================
-- Migration: 00043_hrm_calendar_events
--
-- HRM calendar — Group E3.
-- Integrates with C4 (hrm_acknowledgements) for RSVP.
--
-- Event types:
--   holiday         → public holiday (linked to A6 holiday calendar entries)
--   training        → training sessions
--   company_event   → org-wide gatherings
--   team_event      → department/team events
--   deadline        → submission/compliance deadlines
--   birthday        → employee birthdays (auto-generated by E4)
--   work_anniversary→ work anniversaries (auto-generated by E4)
--   custom          → HR-defined
--
-- RSVP (C4 integration):
--   When requires_rsvp = TRUE, creating or publishing the event
--   creates hrm_acknowledgements rows (acknowledgeable_type='calendar_event')
--   for each target employee. Employees respond via the C4 endpoint.
-- ============================================================

CREATE TABLE hrm_calendar_events (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    public_id        TEXT        NOT NULL UNIQUE
                                     DEFAULT ('cal_' || REPLACE(gen_random_uuid()::TEXT, '-', '')),
    org_id           UUID        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

    title            TEXT        NOT NULL,
    description      TEXT,

    event_type       TEXT        NOT NULL DEFAULT 'company_event'
                                     CHECK (event_type IN (
                                         'holiday', 'training', 'company_event', 'team_event',
                                         'deadline', 'birthday', 'work_anniversary', 'custom'
                                     )),

    -- Date/time (dates inclusive)
    start_date       DATE        NOT NULL,
    end_date         DATE        NOT NULL,
    is_all_day       BOOLEAN     NOT NULL DEFAULT TRUE,
    start_time       TIME,               -- NULL if is_all_day=TRUE
    end_time         TIME,               -- NULL if is_all_day=TRUE

    location         TEXT,

    -- Who this event is for
    scope_type       TEXT        NOT NULL DEFAULT 'organization'
                                     CHECK (scope_type IN ('organization', 'department', 'individual')),
    scope_ids        UUID[]      NOT NULL DEFAULT '{}',

    -- C4 RSVP integration
    requires_rsvp    BOOLEAN     NOT NULL DEFAULT FALSE,
    rsvp_deadline    DATE,

    -- Who organised it
    organizer_id     UUID        REFERENCES users(id) ON DELETE SET NULL,

    -- Auto-generated by E4 milestone engine or A6 holiday sync
    is_auto_generated BOOLEAN    NOT NULL DEFAULT FALSE,
    source            TEXT       CHECK (source IN ('milestone', 'holiday_calendar', 'manual', NULL)),
    source_id         UUID,      -- ID of the source record (hrm_employee_milestones.id or A6 holiday ID)

    status           TEXT        NOT NULL DEFAULT 'upcoming'
                                     CHECK (status IN ('upcoming', 'ongoing', 'completed', 'cancelled')),

    created_by       UUID        NOT NULL REFERENCES users(id),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_hrm_cal_dates CHECK (end_date >= start_date)
);

CREATE INDEX idx_hrm_cal_org_id     ON hrm_calendar_events (org_id);
CREATE INDEX idx_hrm_cal_status     ON hrm_calendar_events (org_id, status);
CREATE INDEX idx_hrm_cal_event_type ON hrm_calendar_events (org_id, event_type);
CREATE INDEX idx_hrm_cal_date_range ON hrm_calendar_events (org_id, start_date, end_date);
CREATE INDEX idx_hrm_cal_upcoming   ON hrm_calendar_events (org_id, start_date) WHERE status = 'upcoming';

COMMENT ON TABLE  hrm_calendar_events IS 'HR calendar: holidays, training, company events, deadlines, birthdays, anniversaries';
COMMENT ON COLUMN hrm_calendar_events.requires_rsvp IS 'When true, C4 acknowledgements created for each target employee with type=calendar_event';
COMMENT ON COLUMN hrm_calendar_events.source        IS 'How the event was created: manual|milestone|holiday_calendar';

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS hrm_calendar_events;
-- +goose StatementEnd
