// backend/internal/hrm/milestones/model.go
package milestones

import (
	"errors"
	"time"
)

type MilestoneType string
const (
	TypeWorkAnniversary  MilestoneType = "work_anniversary"
	TypeBirthday         MilestoneType = "birthday"
	TypeProbationComplete MilestoneType = "probation_complete"
	TypePromotion        MilestoneType = "promotion"
	TypeContractRenewal  MilestoneType = "contract_renewal"
	TypeRetirement       MilestoneType = "retirement"
	TypeCustom           MilestoneType = "custom"
)
func (t MilestoneType) IsValid() bool {
	switch t { case TypeWorkAnniversary, TypeBirthday, TypeProbationComplete, TypePromotion, TypeContractRenewal, TypeRetirement, TypeCustom: return true }
	return false
}

// Milestone records a significant employee lifecycle event.
type Milestone struct {
	ID                   string        `db:"id"                    json:"id"`
	PublicID             string        `db:"public_id"             json:"public_id"`
	OrgID                string        `db:"org_id"                json:"org_id"`
	EmployeeID           string        `db:"employee_id"           json:"employee_id"`
	MilestoneType        MilestoneType `db:"milestone_type"        json:"milestone_type"`
	Title                string        `db:"title"                 json:"title"`
	Description          *string       `db:"description"           json:"description,omitempty"`
	MilestoneDate        string        `db:"milestone_date"        json:"milestone_date"`
	YearsCount           *int          `db:"years_count"           json:"years_count,omitempty"`
	IsAutoGenerated      bool          `db:"is_auto_generated"     json:"is_auto_generated"`
	AutoAwardID          *string       `db:"auto_award_id"         json:"auto_award_id,omitempty"`
	AutoAnnouncementID   *string       `db:"auto_announcement_id"  json:"auto_announcement_id,omitempty"`
	AutoCalendarEventID  *string       `db:"auto_calendar_event_id" json:"auto_calendar_event_id,omitempty"`
	IsAcknowledged       bool          `db:"is_acknowledged"       json:"is_acknowledged"`
	AcknowledgedAt       *time.Time    `db:"acknowledged_at"       json:"acknowledged_at,omitempty"`
	CreatedBy            string        `db:"created_by"            json:"created_by"`
	CreatedAt            time.Time     `db:"created_at"            json:"created_at"`
	UpdatedAt            time.Time     `db:"updated_at"            json:"updated_at"`
}

type CreateMilestoneRequest struct {
	EmployeeID     string        `json:"employee_id"`
	MilestoneType  MilestoneType `json:"milestone_type"`
	Title          string        `json:"title"`
	Description    *string       `json:"description"`
	MilestoneDate  string        `json:"milestone_date"`
	YearsCount     *int          `json:"years_count"`
	// Cascade options
	CreateAward         bool    `json:"create_award"`
	CreateAnnouncement  bool    `json:"create_announcement"`
	CreateCalendarEvent bool    `json:"create_calendar_event"`
}

// GenerateRequest bulk-generates milestones for a given year+month
// by scanning active employees' hire dates and DOBs.
type GenerateRequest struct {
	Year  int `json:"year"`
	Month int `json:"month"`
	// Generate work_anniversary milestones
	IncludeAnniversaries bool `json:"include_anniversaries"`
	// Generate birthday milestones (requires dob on employees — if field exists)
	IncludeBirthdays bool `json:"include_birthdays"`
	// Generate probation milestones from A7 contracts
	IncludeProbation bool `json:"include_probation"`
	// Generate contract renewal milestones from A7 contracts
	IncludeContractRenewals bool `json:"include_contract_renewals"`
}

type MilestoneListResponse struct {
	Milestones []*Milestone `json:"milestones"`
	Total      int          `json:"total"`
}

type GenerateResult struct {
	Generated int      `json:"generated"`
	Skipped   int      `json:"skipped"` // already existed (unique constraint)
	Errors    []string `json:"errors,omitempty"`
}

var (
	ErrNotFound              = errors.New("milestone not found")
	ErrEmployeeIDRequired    = errors.New("employee_id is required")
	ErrTitleRequired         = errors.New("title is required")
	ErrInvalidMilestoneType  = errors.New("invalid milestone_type")
	ErrDateRequired          = errors.New("milestone_date is required (YYYY-MM-DD)")
	ErrInvalidDate           = errors.New("date must be a valid YYYY-MM-DD")
	ErrAlreadyAcknowledged   = errors.New("milestone has already been acknowledged")
	ErrDuplicate             = errors.New("milestone already exists for this employee, type, and date")
)
