// backend/internal/hrm/milestones/repository.go
package milestones

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Repository interface {
	FindAll(ctx context.Context, orgID, employeeID, milestoneType string, upcoming bool) ([]*Milestone, error)
	FindByRef(ctx context.Context, orgID, ref string) (*Milestone, error)
	Create(ctx context.Context, m *Milestone) error
	SetCascadeLinks(ctx context.Context, id string, awardID, announcementID, calendarEventID *string) error
	Acknowledge(ctx context.Context, id string) error
}

type repoImpl struct{ db *pgxpool.Pool }
func NewRepository(db *pgxpool.Pool) Repository { return &repoImpl{db: db} }

const sel = `id, public_id, org_id, employee_id, milestone_type,
	title, description, to_char(milestone_date,'YYYY-MM-DD'), years_count,
	is_auto_generated, auto_award_id, auto_announcement_id, auto_calendar_event_id,
	is_acknowledged, acknowledged_at, created_by, created_at, updated_at`

func scan(row pgx.Row) (*Milestone, error) {
	m := &Milestone{}
	err := row.Scan(
		&m.ID, &m.PublicID, &m.OrgID, &m.EmployeeID, &m.MilestoneType,
		&m.Title, &m.Description, &m.MilestoneDate, &m.YearsCount,
		&m.IsAutoGenerated, &m.AutoAwardID, &m.AutoAnnouncementID, &m.AutoCalendarEventID,
		&m.IsAcknowledged, &m.AcknowledgedAt, &m.CreatedBy, &m.CreatedAt, &m.UpdatedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) { return nil, nil }
	if err != nil { return nil, err }
	return m, nil
}

func (r *repoImpl) FindAll(ctx context.Context, orgID, employeeID, milestoneType string, upcoming bool) ([]*Milestone, error) {
	q := `SELECT ` + sel + ` FROM hrm_employee_milestones WHERE org_id=$1`
	args := []any{orgID}
	if employeeID != "" { args = append(args, employeeID); q += fmt.Sprintf(` AND employee_id=$%d`, len(args)) }
	if milestoneType != "" { args = append(args, milestoneType); q += fmt.Sprintf(` AND milestone_type=$%d`, len(args)) }
	if upcoming { q += ` AND milestone_date >= CURRENT_DATE AND is_acknowledged=FALSE` }
	q += ` ORDER BY milestone_date ASC`
	rows, err := r.db.Query(ctx, q, args...)
	if err != nil { return nil, fmt.Errorf("milestones: FindAll: %w", err) }
	defer rows.Close()
	list := make([]*Milestone, 0)
	for rows.Next() { m, err := scan(rows); if err != nil { return nil, err }; list = append(list, m) }
	return list, rows.Err()
}

func (r *repoImpl) FindByRef(ctx context.Context, orgID, ref string) (*Milestone, error) {
	return scan(r.db.QueryRow(ctx,
		`SELECT `+sel+` FROM hrm_employee_milestones WHERE org_id=$1 AND (id::text=$2 OR public_id=$2)`,
		orgID, ref))
}

func (r *repoImpl) Create(ctx context.Context, m *Milestone) error {
	return r.db.QueryRow(ctx,
		`INSERT INTO hrm_employee_milestones
		(org_id, employee_id, milestone_type, title, description, milestone_date, years_count, is_auto_generated, created_by)
		VALUES ($1,$2,$3,$4,$5,$6::date,$7,$8,$9)
		RETURNING id, public_id, created_at, updated_at`,
		m.OrgID, m.EmployeeID, m.MilestoneType, m.Title, m.Description,
		m.MilestoneDate, m.YearsCount, m.IsAutoGenerated, m.CreatedBy,
	).Scan(&m.ID, &m.PublicID, &m.CreatedAt, &m.UpdatedAt)
}

func (r *repoImpl) SetCascadeLinks(ctx context.Context, id string, awardID, announcementID, calendarEventID *string) error {
	_, err := r.db.Exec(ctx,
		`UPDATE hrm_employee_milestones SET
		auto_award_id=COALESCE($1::uuid, auto_award_id),
		auto_announcement_id=COALESCE($2::uuid, auto_announcement_id),
		auto_calendar_event_id=COALESCE($3::uuid, auto_calendar_event_id),
		updated_at=NOW() WHERE id=$4`,
		awardID, announcementID, calendarEventID, id)
	return err
}

func (r *repoImpl) Acknowledge(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx,
		`UPDATE hrm_employee_milestones SET is_acknowledged=TRUE, acknowledged_at=NOW(), updated_at=NOW() WHERE id=$1`, id)
	return err
}
