// backend/internal/hrm/warningtypes/model.go
package warningtypes

import (
	"errors"
	"time"
)

// EscalationAction is what the system does when a threshold is reached.
// By design the system only flags HR — it never auto-creates a warning.
type EscalationAction string

const (
	EscalationActionNotifyHR          EscalationAction = "notify_hr"
	EscalationActionNotifyManagement  EscalationAction = "notify_management"
	EscalationActionFlagTermination   EscalationAction = "flag_termination_review"
)

func (a EscalationAction) IsValid() bool {
	switch a {
	case EscalationActionNotifyHR, EscalationActionNotifyManagement, EscalationActionFlagTermination:
		return true
	}
	return false
}

// WarningType defines a category of warning (Verbal, Written, Final, PIP, etc.).
// This is the config layer — actual issued warnings are in Group C1.
type WarningType struct {
	ID                     string    `db:"id"                       json:"id"`
	PublicID               string    `db:"public_id"                json:"public_id"`
	OrgID                  string    `db:"org_id"                   json:"org_id"`
	Name                   string    `db:"name"                     json:"name"`
	Description            *string   `db:"description"              json:"description,omitempty"`
	SeverityLevel          int       `db:"severity_level"           json:"severity_level"`
	CanBeIssuedBy          []string  `db:"can_be_issued_by"         json:"can_be_issued_by"`
	RequiresHRApproval     bool      `db:"requires_hr_approval"     json:"requires_hr_approval"`
	ApprovalTemplateID     *string   `db:"approval_template_id"     json:"approval_template_id,omitempty"`
	EmployeeCanRespond     bool      `db:"employee_can_respond"     json:"employee_can_respond"`
	ResponseWindowDays     int       `db:"response_window_days"     json:"response_window_days"`
	AutoGenerateDocument   bool      `db:"auto_generate_document"   json:"auto_generate_document"`
	DocumentTemplateID     *string   `db:"document_template_id"     json:"document_template_id,omitempty"`
	ValidDurationDays      int       `db:"valid_duration_days"      json:"valid_duration_days"`
	IsActive               bool      `db:"is_active"                json:"is_active"`
	CreatedBy              string    `db:"created_by"               json:"created_by"`
	CreatedAt              time.Time `db:"created_at"               json:"created_at"`
	UpdatedAt              time.Time `db:"updated_at"               json:"updated_at"`
}

// WarningEscalationRule triggers an HR alert when a count threshold is reached.
type WarningEscalationRule struct {
	ID                    string           `db:"id"                       json:"id"`
	PublicID              string           `db:"public_id"                json:"public_id"`
	OrgID                 string           `db:"org_id"                   json:"org_id"`
	TriggerWarningTypeID  string           `db:"trigger_warning_type_id"  json:"trigger_warning_type_id"`
	TriggerCount          int              `db:"trigger_count"            json:"trigger_count"`
	WithinDays            int              `db:"within_days"              json:"within_days"` // 0 = all-time
	Action                EscalationAction `db:"action"                   json:"action"`
	NotificationRoles     []string         `db:"notification_roles"       json:"notification_roles"`
	IsActive              bool             `db:"is_active"                json:"is_active"`
	CreatedBy             string           `db:"created_by"               json:"created_by"`
	CreatedAt             time.Time        `db:"created_at"               json:"created_at"`
	UpdatedAt             time.Time        `db:"updated_at"               json:"updated_at"`
}

// ─── Request types ────────────────────────────────────────────────────────────

type CreateWarningTypeRequest struct {
	Name                 string   `json:"name"`
	Description          *string  `json:"description"`
	SeverityLevel        *int     `json:"severity_level"`         // 1–10; defaults to 5
	CanBeIssuedBy        []string `json:"can_be_issued_by"`       // role names
	RequiresHRApproval   bool     `json:"requires_hr_approval"`
	ApprovalTemplateID   *string  `json:"approval_template_id"`
	EmployeeCanRespond   bool     `json:"employee_can_respond"`
	ResponseWindowDays   *int     `json:"response_window_days"`   // defaults to 5
	AutoGenerateDocument bool     `json:"auto_generate_document"`
	DocumentTemplateID   *string  `json:"document_template_id"`
	ValidDurationDays    *int     `json:"valid_duration_days"`    // 0 = permanent
}

type UpdateWarningTypeRequest struct {
	Name                 *string  `json:"name"`
	Description          *string  `json:"description"`
	SeverityLevel        *int     `json:"severity_level"`
	CanBeIssuedBy        []string `json:"can_be_issued_by"`
	RequiresHRApproval   *bool    `json:"requires_hr_approval"`
	ApprovalTemplateID   *string  `json:"approval_template_id"`
	EmployeeCanRespond   *bool    `json:"employee_can_respond"`
	ResponseWindowDays   *int     `json:"response_window_days"`
	AutoGenerateDocument *bool    `json:"auto_generate_document"`
	DocumentTemplateID   *string  `json:"document_template_id"`
	ValidDurationDays    *int     `json:"valid_duration_days"`
	IsActive             *bool    `json:"is_active"`
}

type CreateEscalationRuleRequest struct {
	TriggerWarningTypeID string           `json:"trigger_warning_type_id"`
	TriggerCount         int              `json:"trigger_count"`
	WithinDays           *int             `json:"within_days"`
	Action               EscalationAction `json:"action"`
	NotificationRoles    []string         `json:"notification_roles"`
}

type UpdateEscalationRuleRequest struct {
	TriggerCount      *int              `json:"trigger_count"`
	WithinDays        *int              `json:"within_days"`
	Action            *EscalationAction `json:"action"`
	NotificationRoles []string          `json:"notification_roles"`
	IsActive          *bool             `json:"is_active"`
}

// ─── List responses ───────────────────────────────────────────────────────────

type WarningTypeListResponse struct {
	WarningTypes []*WarningType `json:"warning_types"`
	Total        int            `json:"total"`
}

type EscalationRuleListResponse struct {
	Rules []*WarningEscalationRule `json:"rules"`
	Total int                      `json:"total"`
}

// ─── Sentinel errors ──────────────────────────────────────────────────────────

var (
	ErrWarningTypeNotFound      = errors.New("warning type not found")
	ErrEscalationRuleNotFound   = errors.New("escalation rule not found")
	ErrNameRequired             = errors.New("name is required")
	ErrNameTooLong              = errors.New("name must not exceed 100 characters")
	ErrNameConflict             = errors.New("a warning type with this name already exists")
	ErrInvalidSeverityLevel     = errors.New("severity_level must be between 1 and 10")
	ErrInvalidAction            = errors.New("invalid escalation action")
	ErrTriggerCountRequired     = errors.New("trigger_count must be >= 1")
	ErrTriggerTypeRequired      = errors.New("trigger_warning_type_id is required")
)
