// backend/internal/hrm/warningtypes/repository.go
package warningtypes

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Repository defines data access for HRM warning type configuration.
type Repository interface {
	FindAllTypes(ctx context.Context, orgID string, activeOnly bool) ([]*WarningType, error)
	FindTypeByRef(ctx context.Context, orgID, ref string) (*WarningType, error)
	CreateType(ctx context.Context, wt *WarningType) error
	UpdateType(ctx context.Context, wt *WarningType) error
	DeleteType(ctx context.Context, orgID, ref string) error
	TypeNameExists(ctx context.Context, orgID, name, excludeID string) (bool, error)

	FindEscalationRules(ctx context.Context, orgID, warningTypeID string) ([]*WarningEscalationRule, error)
	FindEscalationRuleByRef(ctx context.Context, orgID, ref string) (*WarningEscalationRule, error)
	CreateEscalationRule(ctx context.Context, r *WarningEscalationRule) error
	UpdateEscalationRule(ctx context.Context, r *WarningEscalationRule) error
	DeleteEscalationRule(ctx context.Context, orgID, ref string) error
}

type repoImpl struct{ db *pgxpool.Pool }

func NewRepository(db *pgxpool.Pool) Repository { return &repoImpl{db: db} }

const wtSelect = `id, public_id, org_id, name, description, severity_level,
	can_be_issued_by, requires_hr_approval, approval_template_id,
	employee_can_respond, response_window_days,
	auto_generate_document, document_template_id,
	valid_duration_days, is_active, created_by, created_at, updated_at`

func scanWarningType(row pgx.Row) (*WarningType, error) {
	wt := &WarningType{}
	err := row.Scan(
		&wt.ID, &wt.PublicID, &wt.OrgID, &wt.Name, &wt.Description, &wt.SeverityLevel,
		&wt.CanBeIssuedBy, &wt.RequiresHRApproval, &wt.ApprovalTemplateID,
		&wt.EmployeeCanRespond, &wt.ResponseWindowDays,
		&wt.AutoGenerateDocument, &wt.DocumentTemplateID,
		&wt.ValidDurationDays, &wt.IsActive, &wt.CreatedBy, &wt.CreatedAt, &wt.UpdatedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) { return nil, nil }
	if err != nil { return nil, err }
	return wt, nil
}

func (r *repoImpl) FindAllTypes(ctx context.Context, orgID string, activeOnly bool) ([]*WarningType, error) {
	q := `SELECT ` + wtSelect + ` FROM hrm_warning_types WHERE org_id=$1`
	if activeOnly { q += ` AND is_active=TRUE` }
	q += ` ORDER BY severity_level DESC, name`
	rows, err := r.db.Query(ctx, q, orgID)
	if err != nil { return nil, fmt.Errorf("warningtypes: FindAllTypes: %w", err) }
	defer rows.Close()
	list := make([]*WarningType, 0)
	for rows.Next() {
		wt, err := scanWarningType(rows)
		if err != nil { return nil, err }
		list = append(list, wt)
	}
	return list, rows.Err()
}

func (r *repoImpl) FindTypeByRef(ctx context.Context, orgID, ref string) (*WarningType, error) {
	q := `SELECT ` + wtSelect + ` FROM hrm_warning_types WHERE org_id=$1 AND (id::text=$2 OR public_id=$2)`
	return scanWarningType(r.db.QueryRow(ctx, q, orgID, ref))
}

func (r *repoImpl) CreateType(ctx context.Context, wt *WarningType) error {
	return r.db.QueryRow(ctx,
		`INSERT INTO hrm_warning_types
		(org_id,name,description,severity_level,can_be_issued_by,
		 requires_hr_approval,approval_template_id,
		 employee_can_respond,response_window_days,
		 auto_generate_document,document_template_id,
		 valid_duration_days,is_active,created_by)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
		RETURNING id, public_id, created_at, updated_at`,
		wt.OrgID, wt.Name, wt.Description, wt.SeverityLevel, wt.CanBeIssuedBy,
		wt.RequiresHRApproval, wt.ApprovalTemplateID,
		wt.EmployeeCanRespond, wt.ResponseWindowDays,
		wt.AutoGenerateDocument, wt.DocumentTemplateID,
		wt.ValidDurationDays, wt.IsActive, wt.CreatedBy,
	).Scan(&wt.ID, &wt.PublicID, &wt.CreatedAt, &wt.UpdatedAt)
}

func (r *repoImpl) UpdateType(ctx context.Context, wt *WarningType) error {
	return r.db.QueryRow(ctx,
		`UPDATE hrm_warning_types SET
		name=$1, description=$2, severity_level=$3, can_be_issued_by=$4,
		requires_hr_approval=$5, approval_template_id=$6,
		employee_can_respond=$7, response_window_days=$8,
		auto_generate_document=$9, document_template_id=$10,
		valid_duration_days=$11, is_active=$12, updated_at=NOW()
		WHERE id=$13 AND org_id=$14 RETURNING updated_at`,
		wt.Name, wt.Description, wt.SeverityLevel, wt.CanBeIssuedBy,
		wt.RequiresHRApproval, wt.ApprovalTemplateID,
		wt.EmployeeCanRespond, wt.ResponseWindowDays,
		wt.AutoGenerateDocument, wt.DocumentTemplateID,
		wt.ValidDurationDays, wt.IsActive, wt.ID, wt.OrgID,
	).Scan(&wt.UpdatedAt)
}

func (r *repoImpl) DeleteType(ctx context.Context, orgID, ref string) error {
	cmd, err := r.db.Exec(ctx, `DELETE FROM hrm_warning_types WHERE org_id=$1 AND (id::text=$2 OR public_id=$2)`, orgID, ref)
	if err != nil { return fmt.Errorf("warningtypes: DeleteType: %w", err) }
	if cmd.RowsAffected() == 0 { return ErrWarningTypeNotFound }
	return nil
}

func (r *repoImpl) TypeNameExists(ctx context.Context, orgID, name, excludeID string) (bool, error) {
	var exists bool
	err := r.db.QueryRow(ctx,
		`SELECT EXISTS(SELECT 1 FROM hrm_warning_types WHERE org_id=$1 AND LOWER(name)=LOWER($2) AND is_active=TRUE AND id::text!=$3)`,
		orgID, name, excludeID).Scan(&exists)
	return exists, err
}

const ruleSelect = `id, public_id, org_id, trigger_warning_type_id, trigger_count, within_days, action, notification_roles, is_active, created_by, created_at, updated_at`

func scanRule(row pgx.Row) (*WarningEscalationRule, error) {
	r := &WarningEscalationRule{}
	err := row.Scan(&r.ID, &r.PublicID, &r.OrgID, &r.TriggerWarningTypeID,
		&r.TriggerCount, &r.WithinDays, &r.Action, &r.NotificationRoles,
		&r.IsActive, &r.CreatedBy, &r.CreatedAt, &r.UpdatedAt)
	if errors.Is(err, pgx.ErrNoRows) { return nil, nil }
	if err != nil { return nil, err }
	return r, nil
}

func (r *repoImpl) FindEscalationRules(ctx context.Context, orgID, warningTypeID string) ([]*WarningEscalationRule, error) {
	q := `SELECT ` + ruleSelect + ` FROM hrm_warning_escalation_rules WHERE org_id=$1`
	args := []any{orgID}
	if warningTypeID != "" {
		args = append(args, warningTypeID)
		q += fmt.Sprintf(` AND trigger_warning_type_id=$%d`, len(args))
	}
	q += ` ORDER BY trigger_count`
	rows, err := r.db.Query(ctx, q, args...)
	if err != nil { return nil, fmt.Errorf("warningtypes: FindEscalationRules: %w", err) }
	defer rows.Close()
	list := make([]*WarningEscalationRule, 0)
	for rows.Next() {
		ru, err := scanRule(rows)
		if err != nil { return nil, err }
		list = append(list, ru)
	}
	return list, rows.Err()
}

func (r *repoImpl) FindEscalationRuleByRef(ctx context.Context, orgID, ref string) (*WarningEscalationRule, error) {
	q := `SELECT ` + ruleSelect + ` FROM hrm_warning_escalation_rules WHERE org_id=$1 AND (id::text=$2 OR public_id=$2)`
	return scanRule(r.db.QueryRow(ctx, q, orgID, ref))
}

func (r *repoImpl) CreateEscalationRule(ctx context.Context, ru *WarningEscalationRule) error {
	return r.db.QueryRow(ctx,
		`INSERT INTO hrm_warning_escalation_rules
		(org_id,trigger_warning_type_id,trigger_count,within_days,action,notification_roles,is_active,created_by)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
		RETURNING id, public_id, created_at, updated_at`,
		ru.OrgID, ru.TriggerWarningTypeID, ru.TriggerCount, ru.WithinDays,
		ru.Action, ru.NotificationRoles, ru.IsActive, ru.CreatedBy,
	).Scan(&ru.ID, &ru.PublicID, &ru.CreatedAt, &ru.UpdatedAt)
}

func (r *repoImpl) UpdateEscalationRule(ctx context.Context, ru *WarningEscalationRule) error {
	return r.db.QueryRow(ctx,
		`UPDATE hrm_warning_escalation_rules SET
		trigger_count=$1, within_days=$2, action=$3, notification_roles=$4, is_active=$5, updated_at=NOW()
		WHERE id=$6 AND org_id=$7 RETURNING updated_at`,
		ru.TriggerCount, ru.WithinDays, ru.Action, ru.NotificationRoles, ru.IsActive, ru.ID, ru.OrgID,
	).Scan(&ru.UpdatedAt)
}

func (r *repoImpl) DeleteEscalationRule(ctx context.Context, orgID, ref string) error {
	cmd, err := r.db.Exec(ctx, `DELETE FROM hrm_warning_escalation_rules WHERE org_id=$1 AND (id::text=$2 OR public_id=$2)`, orgID, ref)
	if err != nil { return fmt.Errorf("warningtypes: DeleteEscalationRule: %w", err) }
	if cmd.RowsAffected() == 0 { return ErrEscalationRuleNotFound }
	return nil
}
