// backend/internal/hrm/warningtypes/service.go
package warningtypes

import (
	"context"
	"fmt"
	"strings"
)

// Service defines business logic for HRM warning type configuration.
type Service interface {
	ListTypes(ctx context.Context, orgID string, activeOnly bool) (*WarningTypeListResponse, error)
	GetType(ctx context.Context, orgID, ref string) (*WarningType, error)
	CreateType(ctx context.Context, orgID, createdBy string, req CreateWarningTypeRequest) (*WarningType, error)
	UpdateType(ctx context.Context, orgID, ref string, req UpdateWarningTypeRequest) (*WarningType, error)
	DeleteType(ctx context.Context, orgID, ref string) error

	ListEscalationRules(ctx context.Context, orgID, warningTypeID string) (*EscalationRuleListResponse, error)
	GetEscalationRule(ctx context.Context, orgID, ref string) (*WarningEscalationRule, error)
	CreateEscalationRule(ctx context.Context, orgID, createdBy string, req CreateEscalationRuleRequest) (*WarningEscalationRule, error)
	UpdateEscalationRule(ctx context.Context, orgID, ref string, req UpdateEscalationRuleRequest) (*WarningEscalationRule, error)
	DeleteEscalationRule(ctx context.Context, orgID, ref string) error
}

type serviceImpl struct{ repo Repository }

func NewService(repo Repository) Service { return &serviceImpl{repo: repo} }

func (s *serviceImpl) ListTypes(ctx context.Context, orgID string, activeOnly bool) (*WarningTypeListResponse, error) {
	list, err := s.repo.FindAllTypes(ctx, orgID, activeOnly)
	if err != nil { return nil, fmt.Errorf("warningtypes: ListTypes: %w", err) }
	if list == nil { list = []*WarningType{} }
	return &WarningTypeListResponse{WarningTypes: list, Total: len(list)}, nil
}

func (s *serviceImpl) GetType(ctx context.Context, orgID, ref string) (*WarningType, error) {
	wt, err := s.repo.FindTypeByRef(ctx, orgID, ref)
	if err != nil { return nil, fmt.Errorf("warningtypes: GetType: %w", err) }
	if wt == nil { return nil, ErrWarningTypeNotFound }
	return wt, nil
}

func (s *serviceImpl) CreateType(ctx context.Context, orgID, createdBy string, req CreateWarningTypeRequest) (*WarningType, error) {
	name := strings.TrimSpace(req.Name)
	if name == "" { return nil, ErrNameRequired }
	if len(name) > 100 { return nil, ErrNameTooLong }
	if exists, _ := s.repo.TypeNameExists(ctx, orgID, name, ""); exists { return nil, ErrNameConflict }

	severity := 5
	if req.SeverityLevel != nil { severity = *req.SeverityLevel }
	if severity < 1 || severity > 10 { return nil, ErrInvalidSeverityLevel }

	issuedBy := req.CanBeIssuedBy
	if len(issuedBy) == 0 { issuedBy = []string{"admin", "hr_manager"} }

	responseWindow := 5
	if req.ResponseWindowDays != nil { responseWindow = *req.ResponseWindowDays }

	validDuration := 0
	if req.ValidDurationDays != nil { validDuration = *req.ValidDurationDays }

	wt := &WarningType{
		OrgID: orgID, Name: name, Description: req.Description,
		SeverityLevel: severity, CanBeIssuedBy: issuedBy,
		RequiresHRApproval: req.RequiresHRApproval, ApprovalTemplateID: req.ApprovalTemplateID,
		EmployeeCanRespond: req.EmployeeCanRespond, ResponseWindowDays: responseWindow,
		AutoGenerateDocument: req.AutoGenerateDocument, DocumentTemplateID: req.DocumentTemplateID,
		ValidDurationDays: validDuration, IsActive: true, CreatedBy: createdBy,
	}
	if err := s.repo.CreateType(ctx, wt); err != nil { return nil, fmt.Errorf("warningtypes: CreateType: %w", err) }
	return wt, nil
}

func (s *serviceImpl) UpdateType(ctx context.Context, orgID, ref string, req UpdateWarningTypeRequest) (*WarningType, error) {
	wt, err := s.repo.FindTypeByRef(ctx, orgID, ref)
	if err != nil { return nil, fmt.Errorf("warningtypes: UpdateType: %w", err) }
	if wt == nil { return nil, ErrWarningTypeNotFound }

	if req.Name != nil {
		name := strings.TrimSpace(*req.Name)
		if name == "" { return nil, ErrNameRequired }
		if len(name) > 100 { return nil, ErrNameTooLong }
		if exists, _ := s.repo.TypeNameExists(ctx, orgID, name, wt.ID); exists { return nil, ErrNameConflict }
		wt.Name = name
	}
	if req.Description != nil { wt.Description = req.Description }
	if req.SeverityLevel != nil {
		if *req.SeverityLevel < 1 || *req.SeverityLevel > 10 { return nil, ErrInvalidSeverityLevel }
		wt.SeverityLevel = *req.SeverityLevel
	}
	if req.CanBeIssuedBy != nil { wt.CanBeIssuedBy = req.CanBeIssuedBy }
	if req.RequiresHRApproval != nil { wt.RequiresHRApproval = *req.RequiresHRApproval }
	if req.ApprovalTemplateID != nil { wt.ApprovalTemplateID = req.ApprovalTemplateID }
	if req.EmployeeCanRespond != nil { wt.EmployeeCanRespond = *req.EmployeeCanRespond }
	if req.ResponseWindowDays != nil { wt.ResponseWindowDays = *req.ResponseWindowDays }
	if req.AutoGenerateDocument != nil { wt.AutoGenerateDocument = *req.AutoGenerateDocument }
	if req.DocumentTemplateID != nil { wt.DocumentTemplateID = req.DocumentTemplateID }
	if req.ValidDurationDays != nil { wt.ValidDurationDays = *req.ValidDurationDays }
	if req.IsActive != nil { wt.IsActive = *req.IsActive }

	if err := s.repo.UpdateType(ctx, wt); err != nil { return nil, fmt.Errorf("warningtypes: UpdateType: %w", err) }
	return wt, nil
}

func (s *serviceImpl) DeleteType(ctx context.Context, orgID, ref string) error {
	return s.repo.DeleteType(ctx, orgID, ref)
}

func (s *serviceImpl) ListEscalationRules(ctx context.Context, orgID, warningTypeID string) (*EscalationRuleListResponse, error) {
	list, err := s.repo.FindEscalationRules(ctx, orgID, warningTypeID)
	if err != nil { return nil, fmt.Errorf("warningtypes: ListEscalationRules: %w", err) }
	if list == nil { list = []*WarningEscalationRule{} }
	return &EscalationRuleListResponse{Rules: list, Total: len(list)}, nil
}

func (s *serviceImpl) GetEscalationRule(ctx context.Context, orgID, ref string) (*WarningEscalationRule, error) {
	ru, err := s.repo.FindEscalationRuleByRef(ctx, orgID, ref)
	if err != nil { return nil, fmt.Errorf("warningtypes: GetEscalationRule: %w", err) }
	if ru == nil { return nil, ErrEscalationRuleNotFound }
	return ru, nil
}

func (s *serviceImpl) CreateEscalationRule(ctx context.Context, orgID, createdBy string, req CreateEscalationRuleRequest) (*WarningEscalationRule, error) {
	if strings.TrimSpace(req.TriggerWarningTypeID) == "" { return nil, ErrTriggerTypeRequired }
	if req.TriggerCount < 1 { return nil, ErrTriggerCountRequired }
	if !req.Action.IsValid() { return nil, ErrInvalidAction }
	if len(req.NotificationRoles) == 0 { req.NotificationRoles = []string{"admin"} }

	withinDays := 0
	if req.WithinDays != nil { withinDays = *req.WithinDays }

	// Verify the trigger type belongs to this org
	wt, err := s.repo.FindTypeByRef(ctx, orgID, req.TriggerWarningTypeID)
	if err != nil || wt == nil { return nil, ErrWarningTypeNotFound }

	ru := &WarningEscalationRule{
		OrgID: orgID, TriggerWarningTypeID: wt.ID,
		TriggerCount: req.TriggerCount, WithinDays: withinDays,
		Action: req.Action, NotificationRoles: req.NotificationRoles,
		IsActive: true, CreatedBy: createdBy,
	}
	if err := s.repo.CreateEscalationRule(ctx, ru); err != nil { return nil, fmt.Errorf("warningtypes: CreateEscalationRule: %w", err) }
	return ru, nil
}

func (s *serviceImpl) UpdateEscalationRule(ctx context.Context, orgID, ref string, req UpdateEscalationRuleRequest) (*WarningEscalationRule, error) {
	ru, err := s.repo.FindEscalationRuleByRef(ctx, orgID, ref)
	if err != nil { return nil, fmt.Errorf("warningtypes: UpdateEscalationRule: %w", err) }
	if ru == nil { return nil, ErrEscalationRuleNotFound }

	if req.TriggerCount != nil {
		if *req.TriggerCount < 1 { return nil, ErrTriggerCountRequired }
		ru.TriggerCount = *req.TriggerCount
	}
	if req.WithinDays != nil { ru.WithinDays = *req.WithinDays }
	if req.Action != nil {
		if !req.Action.IsValid() { return nil, ErrInvalidAction }
		ru.Action = *req.Action
	}
	if req.NotificationRoles != nil { ru.NotificationRoles = req.NotificationRoles }
	if req.IsActive != nil { ru.IsActive = *req.IsActive }

	if err := s.repo.UpdateEscalationRule(ctx, ru); err != nil { return nil, fmt.Errorf("warningtypes: UpdateEscalationRule: %w", err) }
	return ru, nil
}

func (s *serviceImpl) DeleteEscalationRule(ctx context.Context, orgID, ref string) error {
	return s.repo.DeleteEscalationRule(ctx, orgID, ref)
}
